### ISSUE TITLE
Question about output shape

### ISSUE THREAD

**Issue by tiejun54** [caterinaurban/Libra#4]
Hi,

In your paper, you use polyhedra for backward analysis. But the output of Libra is described by box. Why this is different?

Thanks

**Comment by caterinaurban** [comment]
The output of Libra looks like this:

```
...
✘ Bias Found (y0->x50 vs y1->x51)! in Ranges: x ∈ [0.25, 0.375]:
-8·x + 3 >= 0 ∧ 4·x - 1 >= 0 
...
```

the _box_ `x ∈ [0.25, 0.375]` is a partition of the input space computed by the forward analysis, while the **polyhedra** `-8·x + 3 >= 0 ∧ 4·x - 1 >= 0` indicates the subspace of the partition that is biased.

I hope this helps?

**Comment by caterinaurban** [comment]
I make Libra produce a JSON output in  #5. The JSON format has an explicit 'constraints' field that restricts the box-shaped partition.
